# Generated by Django 2.2 on 2021-03-12 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('project_name', models.CharField(max_length=50, unique=True, verbose_name='项目名称')),
                ('test_user', models.CharField(max_length=200, null=True, verbose_name='测试人员')),
                ('project_ver', models.CharField(max_length=25, verbose_name='版本')),
            ],
            options={
                'verbose_name': '项目信息',
                'db_table': 'ProjectInfo',
            },
        ),
        migrations.CreateModel(
            name='ServerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('server_name', models.CharField(max_length=50, unique=True, verbose_name='服务名称')),
            ],
            options={
                'verbose_name': '服务信息',
                'db_table': 'ServerInfo',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=20, verbose_name='密码')),
                ('station', models.CharField(max_length=20, verbose_name='岗位')),
                ('auth', models.CharField(max_length=20, verbose_name='项目权限')),
            ],
            options={
                'verbose_name': '用户信息',
                'db_table': 'UserInfo',
            },
        ),
        migrations.CreateModel(
            name='TaskInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('task_name', models.CharField(max_length=50, unique=True, verbose_name='任务名称')),
                ('branch_no', models.CharField(max_length=50, verbose_name='比对分支')),
                ('rel_name', models.CharField(max_length=100, null=True, verbose_name='发布名称')),
                ('belong_pro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CodeDiff.ProjectInfo')),
                ('belong_server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CodeDiff.ServerInfo')),
            ],
            options={
                'verbose_name': '任务信息',
                'db_table': 'TaskInfo',
            },
        ),
    ]
